server:
  port: 9001

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/spring?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: spring-test
    password: dkssud123#
  data:
    mysql:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.r2dbc.core: debug
